src/java/Controlador/Beans/CantanteController.java
package Controlador.Beans;

import Modelo.Entidades.Cantante;
import Controlador.Beans.util.JsfUtil;
import Controlador.Beans.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("cantanteController")
@SessionScoped
public class CantanteController implements Serializable {

    @EJB
    private Controlador.Beans.CantanteFacade ejbFacade;
    private List<Cantante> items = null;
    private Cantante selected;

    public CantanteController() {
    }

    public Cantante getSelected() {
        return selected;
    }

    public void setSelected(Cantante selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private CantanteFacade getFacade() {
        return ejbFacade;
    }

    public Cantante prepareCreate() {
        selected = new Cantante();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("CantanteCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("CantanteUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("CantanteDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Cantante> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Cantante getCantante(java.lang.Short id) {
        return getFacade().find(id);
    }

    public List<Cantante> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Cantante> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Cantante.class)
    public static class CantanteControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CantanteController controller = (CantanteController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "cantanteController");
            return controller.getCantante(getKey(value));
        }

        java.lang.Short getKey(String value) {
            java.lang.Short key;
            key = Short.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Short value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Cantante) {
                Cantante o = (Cantante) object;
                return getStringKey(o.getIdcantante());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Cantante.class.getName()});
                return null;
            }
        }

    }

}

web/cantante/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CantanteCreateDlg" widgetVar="CantanteCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateCantanteTitle}">
            <h:form id="CantanteCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cantanteController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateCantanteLabel_idcantante}" for="idcantante" />
                        <p:inputText id="idcantante" value="#{cantanteController.selected.idcantante}" title="#{bundle.CreateCantanteTitle_idcantante}" required="true" requiredMessage="#{bundle.CreateCantanteRequiredMessage_idcantante}"/>
                        <p:outputLabel value="#{bundle.CreateCantanteLabel_nombrecantante}" for="nombrecantante" />
                        <p:inputText id="nombrecantante" value="#{cantanteController.selected.nombrecantante}" title="#{bundle.CreateCantanteTitle_nombrecantante}" required="true" requiredMessage="#{bundle.CreateCantanteRequiredMessage_nombrecantante}"/>
                        <p:outputLabel value="#{bundle.CreateCantanteLabel_nacionalidad}" for="nacionalidad" />
                        <p:inputText id="nacionalidad" value="#{cantanteController.selected.nacionalidad}" title="#{bundle.CreateCantanteTitle_nacionalidad}" required="true" requiredMessage="#{bundle.CreateCantanteRequiredMessage_nacionalidad}"/>
                        <p:outputLabel value="#{bundle.CreateCantanteLabel_edad}" for="edad" />
                        <p:inputText id="edad" value="#{cantanteController.selected.edad}" title="#{bundle.CreateCantanteTitle_edad}" required="true" requiredMessage="#{bundle.CreateCantanteRequiredMessage_edad}"/>
                        <p:outputLabel value="#{bundle.CreateCantanteLabel_nombrecancion}" for="nombrecancion" />
                        <p:inputText id="nombrecancion" value="#{cantanteController.selected.nombrecancion}" title="#{bundle.CreateCantanteTitle_nombrecancion}" required="true" requiredMessage="#{bundle.CreateCantanteRequiredMessage_nombrecancion}"/>
                        <p:outputLabel value="#{bundle.CreateCantanteLabel_idcancion}" for="idcancion" />
                        <p:selectOneMenu id="idcancion" value="#{cantanteController.selected.idcancion}" required="true" requiredMessage="#{bundle.EditCantanteRequiredMessage_idcancion}">
                            <f:selectItems value="#{cancionController.itemsAvailableSelectOne}"
                                           var="idcancionItem"
                                           itemValue="#{idcancionItem}" itemLabel="#{idcancionItem.genero}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{cantanteController.create}" value="#{bundle.Save}" update="display,:CantanteListForm:datalist,:growl" oncomplete="handleSubmit(args,'CantanteCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="CantanteCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/cantante/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CantanteEditDlg" widgetVar="CantanteEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditCantanteTitle}">
            <h:form id="CantanteEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cantanteController.selected != null}">
                        <p:outputLabel value="#{bundle.EditCantanteLabel_idcantante}" for="idcantante" />
                        <p:inputText id="idcantante" value="#{cantanteController.selected.idcantante}" title="#{bundle.EditCantanteTitle_idcantante}" required="true" requiredMessage="#{bundle.EditCantanteRequiredMessage_idcantante}"/>
                        <p:outputLabel value="#{bundle.EditCantanteLabel_nombrecantante}" for="nombrecantante" />
                        <p:inputText id="nombrecantante" value="#{cantanteController.selected.nombrecantante}" title="#{bundle.EditCantanteTitle_nombrecantante}" required="true" requiredMessage="#{bundle.EditCantanteRequiredMessage_nombrecantante}"/>
                        <p:outputLabel value="#{bundle.EditCantanteLabel_nacionalidad}" for="nacionalidad" />
                        <p:inputText id="nacionalidad" value="#{cantanteController.selected.nacionalidad}" title="#{bundle.EditCantanteTitle_nacionalidad}" required="true" requiredMessage="#{bundle.EditCantanteRequiredMessage_nacionalidad}"/>
                        <p:outputLabel value="#{bundle.EditCantanteLabel_edad}" for="edad" />
                        <p:inputText id="edad" value="#{cantanteController.selected.edad}" title="#{bundle.EditCantanteTitle_edad}" required="true" requiredMessage="#{bundle.EditCantanteRequiredMessage_edad}"/>
                        <p:outputLabel value="#{bundle.EditCantanteLabel_nombrecancion}" for="nombrecancion" />
                        <p:inputText id="nombrecancion" value="#{cantanteController.selected.nombrecancion}" title="#{bundle.EditCantanteTitle_nombrecancion}" required="true" requiredMessage="#{bundle.EditCantanteRequiredMessage_nombrecancion}"/>
                        <p:outputLabel value="#{bundle.EditCantanteLabel_idcancion}" for="idcancion" />
                        <p:selectOneMenu id="idcancion" value="#{cantanteController.selected.idcancion}" required="true" requiredMessage="#{bundle.EditCantanteRequiredMessage_idcancion}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{cancionController.itemsAvailableSelectOne}"
                                           var="idcancionItem"
                                           itemValue="#{idcancionItem}" itemLabel="#{idcancionItem.genero}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{cantanteController.update}" value="#{bundle.Save}" update="display,:CantanteListForm:datalist,:growl" oncomplete="handleSubmit(args, 'CantanteEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="CantanteEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/cantante/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListCantanteTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="CantanteListForm">
                <p:panel header="#{bundle.ListCantanteTitle}">
                    <p:dataTable id="datalist" value="#{cantanteController.items}" var="item"
                                 selectionMode="single" selection="#{cantanteController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idcantante}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCantanteTitle_idcantante}"/>
                            </f:facet>
                            <h:outputText value="#{item.idcantante}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCantanteTitle_nombrecantante}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombrecantante}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCantanteTitle_nacionalidad}"/>
                            </f:facet>
                            <h:outputText value="#{item.nacionalidad}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCantanteTitle_edad}"/>
                            </f:facet>
                            <h:outputText value="#{item.edad}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCantanteTitle_nombrecancion}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombrecancion}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCantanteTitle_idcancion}"/>
                            </f:facet>
                            <h:outputText value="#{item.idcancion.genero}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{cantanteController.prepareCreate}" update=":CantanteCreateForm" oncomplete="PF('CantanteCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":CantanteViewForm" oncomplete="PF('CantanteViewDialog').show()" disabled="#{empty cantanteController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":CantanteEditForm" oncomplete="PF('CantanteEditDialog').show()" disabled="#{empty cantanteController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{cantanteController.destroy}" update=":growl,datalist" disabled="#{empty cantanteController.selected}">
                                <p:confirm header="Confirmacion" message="¿Esta seguro de eliminar este cantante?" icon="pi pi-exclamation-triangle"/>
                            </p:commandButton>
                            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                                <p:commandButton value="Si" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check"/>
                                <p:commandButton value="Cancelar" type="button" styleClass="ui-confirmdialog-no" icon="pi pi-check"/>
                            </p:confirmDialog>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/cantante/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CantanteViewDlg" widgetVar="CantanteViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewCantanteTitle}">
            <h:form id="CantanteViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{cantanteController.selected != null}">
                        <h:outputText value="#{bundle.ViewCantanteLabel_idcantante}"/>
                        <h:outputText value="#{cantanteController.selected.idcantante}" title="#{bundle.ViewCantanteTitle_idcantante}"/>
                        <h:outputText value="#{bundle.ViewCantanteLabel_nombrecantante}"/>
                        <h:outputText value="#{cantanteController.selected.nombrecantante}" title="#{bundle.ViewCantanteTitle_nombrecantante}"/>
                        <h:outputText value="#{bundle.ViewCantanteLabel_nacionalidad}"/>
                        <h:outputText value="#{cantanteController.selected.nacionalidad}" title="#{bundle.ViewCantanteTitle_nacionalidad}"/>
                        <h:outputText value="#{bundle.ViewCantanteLabel_edad}"/>
                        <h:outputText value="#{cantanteController.selected.edad}" title="#{bundle.ViewCantanteTitle_edad}"/>
                        <h:outputText value="#{bundle.ViewCantanteLabel_nombrecancion}"/>
                        <h:outputText value="#{cantanteController.selected.nombrecancion}" title="#{bundle.ViewCantanteTitle_nombrecancion}"/>
                        <h:outputText value="#{bundle.ViewCantanteLabel_idcancion}"/>
                        <h:outputText value="#{cantanteController.selected.idcancion.genero}" title="#{bundle.ViewCantanteTitle_idcancion}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="CantanteViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>